from . import savat
from . import savat_ru
from . import zakaz
from . import zakaz_ru
from . import malumotlar
from . import qabul_RU
from . import qabul
from . import til
from . import rek
from . import olib_ketish
from . import olib_ketish_ru
from . import functions
from . import tolov_click_ru
from . import tolov_click
from . import vaqt_tanlash
from . import vaqt_tanlash_ru
